Working page
rloterh/NYTPageClone pull request #2
Opened 2020-06-15 12:10 UTC by rloterh

- Positioned elements using CSS3 grids and flexbox
- Embedded images
- Worked with forms (buttons)
- Applied the box model

2020-06-15 12:56 UTC, HADDADSOHAIB requested changes
### Status: Change Required :recycle: 

### Hello @rloterh  and @eypsrcnuygr  :hand: 

### Good job, you did great job with the project :+1: 

### Unfortunately, there are still some changes to get the project approved:
- Please fix linter errors:
![Screenshot from 2020-06-15 13-34-26](https://user-images.githubusercontent.com/26064042/84657941-fd28cf80-af0c-11ea-9baa-f1d84b87904f.png)
- You have commented code in your project, please delete that.
- [ ] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/no_inline_comments.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- Please fix the validators errors and warnings:
- [ ] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload. (Students were asked to use this one, so in most cases their code should be already validated) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/validation_requirement.png) from Pathwright)
![Screenshot from 2020-06-15 13-39-44](https://user-images.githubusercontent.com/26064042/84658403-c43d2a80-af0d-11ea-922c-3884443e406d.png)
- The logo in the navbar must be a link:
- [ ] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
- The navbar is not similar to the original:
The original:
![Screenshot from 2020-06-15 10-38-49](https://user-images.githubusercontent.com/26064042/84642507-7962e900-aef4-11ea-9311-612d95b30d67.png)
 Your Project:
![Screenshot from 2020-06-15 10-39-36](https://user-images.githubusercontent.com/26064042/84642550-897ac880-aef4-11ea-806c-2ca12ff993dc.png)
- The social media icons should be links, both on the beginning and on the end of the articles:
![Screenshot from 2020-06-15 13-46-01](https://user-images.githubusercontent.com/26064042/84658994-a3c1a000-af0e-11ea-99b1-25ec5602a387.png)
- Editors picks articles should be links as the original:

![Screenshot from 2020-06-15 13-47-15](https://user-images.githubusercontent.com/26064042/84659099-c784e600-af0e-11ea-8c39-3512b69a20e5.png)

- There is a sticky footer on the original, please add that on your project:
![Screenshot from 2020-06-15 10-49-53](https://user-images.githubusercontent.com/26064042/84643719-20945000-aef6-11ea-85dc-4a4ae17e95b3.png)
- I think the proportion of the paragraphs in page layout are off a lot, try to adjust that:
your project:
![Screenshot from 2020-06-15 13-48-06](https://user-images.githubusercontent.com/26064042/84659229-01ee8300-af0f-11ea-82a7-750af21022c4.png)
original:
![Screenshot from 2020-06-15 13-49-50](https://user-images.githubusercontent.com/26064042/84659293-1df22480-af0f-11ea-8db8-3f2fec60fef0.png)
- Please fix the image of the right:
![Screenshot from 2020-06-15 13-50-11](https://user-images.githubusercontent.com/26064042/84659353-34987b80-af0f-11ea-883e-602e4f0cdf30.png)
- The footer is mess up, please fix that, also the article on the footer should be link, all of them, including the images:
![Screenshot from 2020-06-15 13-51-38](https://user-images.githubusercontent.com/26064042/84659589-8d681400-af0f-11ea-9353-f196aa7ecd1b.png)

![Screenshot from 2020-06-15 13-51-46](https://user-images.githubusercontent.com/26064042/84659602-92c55e80-af0f-11ea-8785-5b070559bd6d.png)
![Screenshot from 2020-06-15 13-51-52](https://user-images.githubusercontent.com/26064042/84659615-978a1280-af0f-11ea-9ab2-5e32c04b2be2.png)

### Once you are done with the changes, please asked for another code review. :wave:

2020-06-15 12:56 UTC, HADDADSOHAIB commented on index.html
> +<!--<![endif]-->
Commented code here

2020-06-15 12:56 UTC, HADDADSOHAIB commented on index.html
> +    <![endif]-->
Commented code here

2020-06-16 11:32 UTC, sumancrest0001 commented
**Status: changes required
Hello TEAM.** thank you for making most of the changes requested by the previous TSE. Your project and repository are looking much more professional and clean. But there are still some issues that need to be addressed to get approved. Let's have a look at them.
**[NOTE] All the changes are mandatory.**

1. As stated by the previous TSE, the proportion of the page is different from the original page. Please change it which will give your project a similar look to the original one.

2. Most popular section layout is different from the original page. Please compare them
your :point_down: 
![Screenshot from 2020-06-16 17-10-55](https://user-images.githubusercontent.com/37747619/84769241-3c325000-aff5-11ea-9132-1898897f3e48.png)

Original one :point_down: 
![Screenshot from 2020-06-16 17-11-11](https://user-images.githubusercontent.com/37747619/84769268-46544e80-aff5-11ea-9028-eddb2bd1ab3e.png)

2020-06-16 11:34 UTC, sumancrest0001 commented on css/styles.css
> +}
We have to remove repeated stylings and follow the DRY principle. Please remove all the repeated codes.

2020-06-16 11:36 UTC, sumancrest0001 requested changes
**Kindly make the requested changes and resubmit for another code review.**
If you have any questions regarding the code review, DM me on slack **Suman Shrestha**

**Happy coding :+1:**

2020-06-16 17:15 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Great job implementing the changes 👍. I see that you have made some solid changes. Good job!!

However, we need to work on some changes before we can merge.

- The `inflation-container` is overflowing. I see that you have applied `overflow-x: hidden;` to the body. It's not a solution, it's more like a band-aid. Fix this.

![Annotation 2020-06-16 221847](https://user-images.githubusercontent.com/57726348/84803263-66006c80-b01f-11ea-9883-06d14be90bf5.jpg)

### [OPTIONAL]

- The social icons need to be centered.
![Annotation 2020-06-16 224040](https://user-images.githubusercontent.com/57726348/84806126-d8bf1700-b022-11ea-9a2a-71ab10869207.jpg)

- Increase the width of `article-content`

Apply these changes and request another code review.

Happy coding 👨‍💻

2020-06-17 09:10 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: 
**HELLO** @rloterh :wave: 
**Great work so far. You have implemented the requested changes by the previous TSE**
However, there are a few more changes to be made so that we can approve this project:

- [ ] Kindly improve on your footer section. It doesn't  look like the original
**yours**
![nyt_footer](https://user-images.githubusercontent.com/32361963/84878686-d8f6fb00-b092-11ea-80b4-878dca07b08e.jpg)

**original**
![nyt_footer_original](https://user-images.githubusercontent.com/32361963/84878723-e3b19000-b092-11ea-9940-41b2d7af5170.jpg)

- [ ] Kindly also improve on this section. It needs to look like the original.

**yours**
![sec](https://user-images.githubusercontent.com/32361963/84878988-4acf4480-b093-11ea-9713-986f009d2402.jpg)
**original**
![sec-original](https://user-images.githubusercontent.com/32361963/84879036-5884ca00-b093-11ea-8bc1-ccbc4067b795.jpg)

Also, there are some errors that need fixing in your CSS check below :arrow_down: 

**Kindly submit another code review when you fix all the suggestions**

### HAPPY CODING

2020-06-17 09:10 UTC, peterrobert commented on css/styles.css
> +}
Font-size is a unit. You need to add px for pixels

2020-06-17 09:10 UTC, peterrobert commented on css/styles.css
> +}
You have an extra three on the color.

2020-06-17 11:21 UTC, peterrobert requested changes
### CHANGES REQUIRED :recycle: 
There are still some changes to be made in your project. Kindly you haven't made the previous changes requested. You need to make your webpage look like the original. :smile: 

- [ ] Also kindly try to improve this section.
![fill](https://user-images.githubusercontent.com/32361963/84891785-1bc1ce80-b0a5-11ea-9c8a-f8618fa42129.jpg)
 Kindly if you compare it with the original yours is not well aligned.

**once you make those changes kindly submit your work for another review**

If you have any questions concerning the review you can contact me on @peterrobert 

### HAPPY CODING :muscle:

2020-06-17 13:18 UTC, HADDADSOHAIB requested changes
### Status: Change Required :recycle: 

### Hello @rloterh and @eypsrcnuygr    :hand: 

### Good job, you did great job with the project :+1: 

### Unfortunately, the proportion of your page elements are still off, a lot, learning how to size and place an element is a necessary skill and that the goal of this project, please take the time to master that, you will need it later. I will attach some screen shot to show how your project appears in my browser:
![Screenshot from 2020-06-17 14-09-12](https://user-images.githubusercontent.com/26064042/84902017-2891f280-b0a4-11ea-8ab0-dc90d45ec181.png)
This part is great.
![Screenshot from 2020-06-17 14-09-55](https://user-images.githubusercontent.com/26064042/84902083-40697680-b0a4-11ea-83c5-0ca69a217598.png)
The width of the paragraph is tiny.
![Screenshot from 2020-06-17 14-10-36](https://user-images.githubusercontent.com/26064042/84902150-5840fa80-b0a4-11ea-8841-0a5d0d14fea3.png)
This also very small.
![Screenshot from 2020-06-17 14-11-17](https://user-images.githubusercontent.com/26064042/84902231-6f7fe800-b0a4-11ea-9fe1-cf28aa013ce7.png)
[Optional]This is great, but you can improve by positioning the element in the center, it is not well centered. 
![Screenshot from 2020-06-17 14-13-34](https://user-images.githubusercontent.com/26064042/84902462-c1287280-b0a4-11ea-83b6-a7afb637b71f.png)
The width of the article should be the same as the image, so make the article larger then that, you can keep the image on the same size or make it just a little smaller. Follow the original project layout.
![Screenshot from 2020-06-17 14-15-44](https://user-images.githubusercontent.com/26064042/84902752-1fedec00-b0a5-11ea-875e-da7a989520e5.png)
This part should take the full width.

### once you are done with the changes, please ask for another code review. :+1:

2020-06-17 18:08 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
***All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.***
- Congratulations on the splendid job! :+1:
- You can now merge to master. I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-06-18 09:26 UTC, rloterh commented
Resolved issues

2020-06-18 09:26 UTC, rloterh commented
Resolved Issues

2020-06-18 09:57 UTC, merged